language: c
sudo: false
script:
  - gcc tests/src/*.c -I tests/include -lcriterion --coverage -o codecov
  - ./codecov
  - gcov tests/src/*.c

after_success:
  - bash <(curl -s https://codecov.io/bash)